/**
 * Daily task engine — the orchestrator behind the 23:55 → 00:00 workflow.
 *
 *   23:55  collectDailyContext()   → full context snapshot (weather + ET₀ +
 *                                   volumes + crop/stage/soil/wilaya)
 *   00:00  generateDailyTaskSet()  → AI (Gemini / OpenAI) task JSON, with the
 *                                   local rule-based generator as the
 *                                   never-fail fallback
 *          publishTaskSet()        → indexed by date (`YYYY-MM-DD`) in RTDB
 *                                   when configured (LocalStorage caching is
 *                                   client-side — see `store.ts`)
 *
 * Server-only concerns (LLM keys, RTDB REST) live here; every function
 * degrades gracefully and never throws, exactly like the assistant route.
 */

import {
  collectDailyContext,
  targetDate,
  type DailyContext,
  type DailyContextInput,
} from "./context";
import { generateAiTasks, type FetchLike } from "./ai";
import { generateRuleTasks } from "./rules";
import { contextKeyFor, type DailyTaskSet, type DailyTaskSource } from "./types";
import { DEFAULT_WILAYA_CODE, getWilaya } from "../wilayas";

/** The published-at stamp the card footer quotes: "اليوم 00:00". */
export const PUBLISH_SLOT = "00:00";

export interface GenerationResult {
  set: DailyTaskSet;
  /** The context the tasks were actually built from (live or reference). */
  context: DailyContext;
  /** Non-fatal degradations (AI offline → rules, RTDB missing…). */
  warnings: string[];
}

/**
 * Builds the day's task set for one context: AI first (Gemini → OpenAI),
 * rule-based fallback last. Guaranteed to return 3–5 valid tasks — the rule
 * engine is deterministic and pure. Never throws.
 */
export async function generateDailyTaskSet(
  input: DailyContextInput & { fetchImpl?: FetchLike; context?: DailyContext },
): Promise<GenerationResult> {
  const warnings: string[] = [];
  const ctx =
    input.context ??
    (await collectDailyContext(input, { fetchImpl: input.fetchImpl }));

  let tasks = null;
  let source: DailyTaskSource = "rules";
  try {
    const ai = await generateAiTasks(ctx, input.fetchImpl);
    if (ai) {
      tasks = ai.tasks;
      source = "ai";
    } else {
      warnings.push("AI providers unavailable — tasks generated by the local rule engine.");
    }
  } catch (error) {
    warnings.push(
      `AI generation failed — local rule engine used: ${error instanceof Error ? error.message : String(error)}`.slice(0, 300),
    );
  }
  if (!tasks) tasks = generateRuleTasks(ctx);

  const set: DailyTaskSet = {
    date: ctx.date,
    contextKey: contextKeyFor({
      wilayaCode: ctx.wilaya.code,
      crop: ctx.crop.key,
      soil: ctx.soil.key,
      areaHa: ctx.areaHa,
    }),
    tasks,
    source,
    generatedAt: new Date().toISOString(),
    publishedAt: PUBLISH_SLOT,
  };
  return { set, context: ctx, warnings };
}

/* ------------------------------------------------------------------ */
/*  RTDB persistence (optional) — `dailyTasks/{date}/{contextKey}`     */
/* ------------------------------------------------------------------ */

/**
 * Realtime Database REST endpoint. Configured via `FIREBASE_DATABASE_URL`
 * (server-only) + optional `FIREBASE_DATABASE_AUTH` (`?auth=` secret/token).
 * When unset, publish/read are no-ops and the client keeps using its
 * LocalStorage cache + on-demand generation.
 */
export function rtdbConfig(): { url: string; auth: string | null } | null {
  const raw = (
    process.env.FIREBASE_DATABASE_URL ??
    process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL ??
    ""
  ).trim();
  if (!/^https:\/\//.test(raw)) return null;
  return {
    url: raw.replace(/\/+$/, ""),
    auth: (process.env.FIREBASE_DATABASE_AUTH ?? "").trim() || null,
  };
}

function rtdbUrl(base: string, path: string, auth: string | null): string {
  return `${base}/${path}.json${auth ? `?auth=${encodeURIComponent(auth)}` : ""}`;
}

/** RTDB rejects `. # $ [ ] /` in keys — contextKeyFor already avoids them. */
export function taskSetPath(date: string, contextKey: string): string {
  return `dailyTasks/${date}/${contextKey}`;
}

export function snapshotPath(date: string, contextKey: string): string {
  return `dailySnapshots/${date}/${contextKey}`;
}

/**
 * Publishes one generated day of tasks under its `YYYY-MM-DD` index.
 * Returns `true` when the write succeeded (or RTDB is unconfigured — the
 * caller's LocalStorage cache is then the only store, which is fine).
 */
export async function publishTaskSet(set: DailyTaskSet, fetchImpl?: FetchLike): Promise<boolean> {
  const cfg = rtdbConfig();
  if (!cfg) return true;
  const impl = fetchImpl ?? (typeof fetch === "function" ? (fetch as FetchLike) : undefined);
  if (!impl) return true;
  try {
    const res = await impl(rtdbUrl(cfg.url, taskSetPath(set.date, set.contextKey), cfg.auth), {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(set),
    });
    return Boolean(res && res.ok);
  } catch {
    return false;
  }
}

/** Reads a published set (`null` when absent / unconfigured / unreachable). */
export async function readPublishedTaskSet(
  date: string,
  contextKey: string,
  fetchImpl?: FetchLike,
): Promise<DailyTaskSet | null> {
  const cfg = rtdbConfig();
  if (!cfg) return null;
  const impl = fetchImpl ?? (typeof fetch === "function" ? (fetch as FetchLike) : undefined);
  if (!impl) return null;
  try {
    const res = await impl(rtdbUrl(cfg.url, taskSetPath(date, contextKey), cfg.auth));
    if (!res || !res.ok) return null;
    const parsed = (await res.json()) as Partial<DailyTaskSet> | null;
    if (!parsed || !Array.isArray(parsed.tasks) || parsed.tasks.length === 0) return null;
    return { ...parsed, date, contextKey } as DailyTaskSet;
  } catch {
    return null;
  }
}

/* ------------------------------------------------------------------ */
/*  23:55 snapshot store                                              */
/* ------------------------------------------------------------------ */

/** In-memory fallback so the two cron phases share data on one instance. */
const snapshotMemory = new Map<string, string>(); // `${date}|${contextKey}` → JSON

/** Stores the collected context snapshot (RTDB + instance memory). */
export async function publishSnapshot(ctx: DailyContext, fetchImpl?: FetchLike): Promise<void> {
  const key = contextKeyFor({
    wilayaCode: ctx.wilaya.code,
    crop: ctx.crop.key,
    soil: ctx.soil.key,
    areaHa: ctx.areaHa,
  });
  snapshotMemory.set(`${ctx.date}|${key}`, JSON.stringify(ctx));
  const cfg = rtdbConfig();
  const impl = fetchImpl ?? (typeof fetch === "function" ? (fetch as FetchLike) : undefined);
  if (!cfg || !impl) return;
  try {
    await impl(rtdbUrl(cfg.url, snapshotPath(ctx.date, key), cfg.auth), {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(ctx),
    });
  } catch {
    /* memory copy still serves this instance */
  }
}

/** Reads back a stored snapshot (memory first, then RTDB). */
export async function readSnapshot(
  date: string,
  contextKey: string,
  fetchImpl?: FetchLike,
): Promise<DailyContext | null> {
  const mem = snapshotMemory.get(`${date}|${contextKey}`);
  if (mem) {
    try {
      return JSON.parse(mem) as DailyContext;
    } catch {
      /* fall through */
    }
  }
  const cfg = rtdbConfig();
  const impl = fetchImpl ?? (typeof fetch === "function" ? (fetch as FetchLike) : undefined);
  if (!cfg || !impl) return null;
  try {
    const res = await impl(rtdbUrl(cfg.url, snapshotPath(date, contextKey), cfg.auth));
    if (!res || !res.ok) return null;
    return (await res.json()) as DailyContext;
  } catch {
    return null;
  }
}

/* ------------------------------------------------------------------ */
/*  Scheduled entrypoints (the cron handlers call these)               */
/* ------------------------------------------------------------------ */

export interface WorkflowRun {
  phase: "snapshot" | "generate";
  date: string;
  runs: Array<{
    contextKey: string;
    ok: boolean;
    source?: DailyTaskSource;
    taskCount?: number;
    warnings: string[];
  }>;
}

/** One pinned parcel context the midnight job publishes for. */
export interface PinnedContext extends DailyContextInput {
  wilayaCode: string;
  crop: DailyContext["crop"]["key"];
}

/**
 * Contexts the cron publishes daily: `DAILY_TASK_CONTEXTS` (JSON array of
 * `{ wilayaCode, crop, soil, areaHa, system }`) plus the app's default wilaya
 * + its lead crop, so there is always at least one published day.
 */
export function pinnedContexts(): PinnedContext[] {
  const out: PinnedContext[] = [];
  const raw = (process.env.DAILY_TASK_CONTEXTS ?? "").trim();
  if (raw) {
    try {
      const parsed = JSON.parse(raw) as Array<Partial<PinnedContext>>;
      for (const entry of parsed) {
        if (entry && typeof entry.wilayaCode === "string" && typeof entry.crop === "string") {
          out.push({ wilayaCode: entry.wilayaCode, crop: entry.crop, ...entry });
        }
      }
    } catch {
      /* malformed env → default context below */
    }
  }
  if (out.length === 0) {
    // First-run default: the app's default wilaya and its lead crop — the
    // same parcel a brand-new user lands on.
    const fallback = getWilaya(DEFAULT_WILAYA_CODE);
    out.push({
      wilayaCode: DEFAULT_WILAYA_CODE,
      crop: fallback.crops[0],
      soil: fallback.soil,
      areaHa: 2,
      system: "drip",
    });
  }
  return out;
}

/** Phase 1 (23:55): collect + store the full context snapshot per context. */
export async function runSnapshotPhase(fetchImpl?: FetchLike, nowMs?: number): Promise<WorkflowRun> {
  const date = targetDate(nowMs);
  const runs: WorkflowRun["runs"] = [];
  for (const pinned of pinnedContexts()) {
    const warnings: string[] = [];
    try {
      const ctx = await collectDailyContext({ ...pinned, date, nowMs }, { fetchImpl });
      if (!ctx.weather.live) warnings.push("Open-Meteo unreachable — reference climate used for the snapshot.");
      await publishSnapshot(ctx, fetchImpl);
      runs.push({
        contextKey: `${ctx.wilaya.code}|${ctx.crop.key}`,
        ok: true,
        warnings,
      });
    } catch (error) {
      runs.push({
        contextKey: `${pinned.wilayaCode}|${pinned.crop}`,
        ok: false,
        warnings: [error instanceof Error ? error.message : String(error)],
      });
    }
  }
  return { phase: "snapshot", date, runs };
}

/** Phase 2 (00:00): AI-generate (rules fallback) + publish for `date`. */
export async function runGeneratePhase(fetchImpl?: FetchLike, nowMs?: number): Promise<WorkflowRun> {
  const date = targetDate(nowMs);
  const runs: WorkflowRun["runs"] = [];
  for (const pinned of pinnedContexts()) {
    const warnings: string[] = [];
    try {
      const soil = pinned.soil ?? getWilaya(pinned.wilayaCode).soil;
      const areaHa = pinned.areaHa ?? 2;
      const contextKey = contextKeyFor({
        wilayaCode: pinned.wilayaCode,
        crop: pinned.crop,
        soil,
        areaHa,
      });
      // Use the 23:55 snapshot when it exists; collect fresh otherwise (the
      // workflow must publish even if the first cron run was missed).
      const stored = await readSnapshot(date, contextKey, fetchImpl);
      const { set, warnings: genWarnings } = await generateDailyTaskSet({
        ...pinned,
        soil,
        areaHa,
        date,
        nowMs,
        fetchImpl,
        ...(stored ? { context: stored } : {}),
      });
      warnings.push(...genWarnings);
      await publishTaskSet(set, fetchImpl);
      runs.push({
        contextKey,
        ok: true,
        source: set.source,
        taskCount: set.tasks.length,
        warnings,
      });
    } catch (error) {
      runs.push({
        contextKey: `${pinned.wilayaCode}|${pinned.crop}`,
        ok: false,
        warnings: [error instanceof Error ? error.message : String(error)],
      });
    }
  }
  return { phase: "generate", date, runs };
}
